# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby_apk 2.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "android_parser".freeze
  s.version = "2.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["SecureBrain".freeze]
  s.date = "2021-08-04"
  s.description = "static analysis tool for android apk".freeze
  s.email = "info@securebrain.co.jp".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files    = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  s.homepage = "https://github.com/SecureBrain/ruby_apk/".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "static analysis tool for android apk".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyzip>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec-its>.freeze, [">= 1.2.0"])
      s.add_development_dependency(%q<rspec-collection_matchers>.freeze, [">= 1.1.0"])
      s.add_development_dependency(%q<rspec-mocks>.freeze, [">= 3.6.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.1.5"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<yard>.freeze, [">= 0"])
      s.add_development_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rubyzip>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<rspec-its>.freeze, [">= 1.2.0"])
      s.add_dependency(%q<rspec-collection_matchers>.freeze, [">= 1.1.0"])
      s.add_dependency(%q<rspec-mocks>.freeze, [">= 3.6.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.1.5"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<yard>.freeze, [">= 0"])
      s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rubyzip>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<rspec-its>.freeze, [">= 1.2.0"])
    s.add_dependency(%q<rspec-collection_matchers>.freeze, [">= 1.1.0"])
    s.add_dependency(%q<rspec-mocks>.freeze, [">= 3.6.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.1.5"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<yard>.freeze, [">= 0"])
    s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

