# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby_apk 2.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby_apk".freeze
  s.version = "2.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["SecureBrain".freeze]
  s.date = "2022-06-15"
  s.description = "static analysis tool for android apk".freeze
  s.email = "info@securebrain.co.jp".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/android/apk.rb",
    "lib/android/axml_parser.rb",
    "lib/android/axml_writer.rb",
    "lib/android/dex.rb",
    "lib/android/dex/access_flag.rb",
    "lib/android/dex/dex_object.rb",
    "lib/android/dex/info.rb",
    "lib/android/dex/utils.rb",
    "lib/android/layout.rb",
    "lib/android/manifest.rb",
    "lib/android/resource.rb",
    "lib/android/utils.rb",
    "lib/ruby_apk.rb",
    "ruby_apk.gemspec",
    "spec/apk_spec.rb",
    "spec/axml_parser_spec.rb",
    "spec/data/sample.apk",
    "spec/data/sample_AndroidManifest.xml",
    "spec/data/sample_AndroidManifest_with_namespaces.xml",
    "spec/data/sample_AndroidManifest_with_redundant_intentfilters.xml",
    "spec/data/sample_AndroidManifest_with_transitive_namespace_declaration.xml",
    "spec/data/sample_classes.dex",
    "spec/data/sample_resources.arsc",
    "spec/data/sample_resources_utf16.arsc",
    "spec/data/str_resources.arsc",
    "spec/dex/access_flag_spec.rb",
    "spec/dex/dex_object_spec.rb",
    "spec/dex/info_spec.rb",
    "spec/dex/utils_spec.rb",
    "spec/dex_spec.rb",
    "spec/layout_spec.rb",
    "spec/manifest_spec.rb",
    "spec/resource_spec.rb",
    "spec/ruby_apk_spec.rb",
    "spec/spec_helper.rb",
    "spec/utils_spec.rb"
  ]
  s.homepage = "https://github.com/SecureBrain/ruby_apk/".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "static analysis tool for android apk".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyzip>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec-its>.freeze, [">= 1.2.0"])
      s.add_development_dependency(%q<rspec-collection_matchers>.freeze, [">= 1.1.0"])
      s.add_development_dependency(%q<rspec-mocks>.freeze, [">= 3.6.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.1.5"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<yard>.freeze, [">= 0"])
      s.add_development_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rubyzip>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<rspec-its>.freeze, [">= 1.2.0"])
      s.add_dependency(%q<rspec-collection_matchers>.freeze, [">= 1.1.0"])
      s.add_dependency(%q<rspec-mocks>.freeze, [">= 3.6.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.1.5"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<yard>.freeze, [">= 0"])
      s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rubyzip>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<rspec-its>.freeze, [">= 1.2.0"])
    s.add_dependency(%q<rspec-collection_matchers>.freeze, [">= 1.1.0"])
    s.add_dependency(%q<rspec-mocks>.freeze, [">= 3.6.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.1.5"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<yard>.freeze, [">= 0"])
    s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

